services:
  db:
    image: postgres
    container_name: db_avalia
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=wikiprof"
    volumes:
      - "/home/gabriel/wikiprof_bd:/var/lib/postgresql/data"
      - "./backend/populate.sql:/var/lib/postgresql/populate.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-d", "wikiprof"]
      interval: 3s
      timeout: 50s
      retries: 10

  backend:
    build:
      dockerfile: "./backend/Dockerfile"
    container_name: back_wikiprof
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - "./backend/populate.sql:/populate.sql"

  frontend:
    build:
      dockerfile: "./frontend/Dockerfile"
    container_name: front_wikiprof
    ports:
      - "3000:3000"
