services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=wikiprof"
    volumes:
      - "/home/gabriel/wikiprof_bd:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-d", "wikiprof"]
      interval: 3s
      timeout: 50s
      retries: 10

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: "service_healthy"
